-- Migration: Add document_structure column to conversion_jobs
-- Story 4.3: AI-Powered Structure Recognition & TOC Generation
-- Date: 2025-12-13
--
-- Adds JSONB column to store AI-detected document structure including
-- table of contents (TOC), chapter metadata, and hierarchy information.

-- Add document_structure JSONB column
ALTER TABLE conversion_jobs
ADD COLUMN IF NOT EXISTS document_structure JSONB;

-- Create GIN index for efficient JSON queries on document_structure
-- GIN indexes enable fast searches within JSONB data
CREATE INDEX IF NOT EXISTS idx_conversion_jobs_document_structure
ON conversion_jobs USING GIN(document_structure)
WHERE document_structure IS NOT NULL;

-- Add column comment for documentation
COMMENT ON COLUMN conversion_jobs.document_structure IS
'AI-detected document structure including TOC, chapters, and hierarchy. Generated by Story 4.3 structure analysis. Contains: title, author, language, toc (items, total_entries, max_depth), chapters (chapter_num, title, start_page, end_page, subsections), confidence_score, and analysis_method (ai_full/ai_chunked/heuristic_fallback).';

-- Optional: Add check constraint to validate document_structure schema
-- (Basic validation - full validation handled by Pydantic models in application)
-- Uncomment if you want database-level validation:
-- ALTER TABLE conversion_jobs
-- ADD CONSTRAINT document_structure_valid_json
-- CHECK (
--     document_structure IS NULL OR
--     (
--         document_structure ? 'title' AND
--         document_structure ? 'language' AND
--         document_structure ? 'toc' AND
--         document_structure ? 'chapters' AND
--         document_structure ? 'confidence_score'
--     )
-- );
