"""
Progress Update Schemas

Pydantic models for real-time conversion progress updates.
Optimized for lightweight polling payloads.
"""
from pydantic import BaseModel, Field, ConfigDict, field_validator
from datetime import datetime
from typing import Optional


class ElementsDetected(BaseModel):
    """
    Live count of detected elements during conversion.

    Attributes:
        tables: Number of tables detected
        images: Number of images found
        equations: Number of equations preserved
        chapters: Number of chapters identified
    """
    tables: int = Field(default=0, ge=0, description="Number of tables detected")
    images: int = Field(default=0, ge=0, description="Number of images found")
    equations: int = Field(default=0, ge=0, description="Number of equations preserved")
    chapters: int = Field(default=0, ge=0, description="Number of chapters identified")

    model_config = ConfigDict(json_schema_extra={
        "example": {
            "tables": 12,
            "images": 8,
            "equations": 5,
            "chapters": 15
        }
    })


class TokenUsage(BaseModel):
    """
    Token usage for AI cost estimation.

    Attributes:
        prompt_tokens: Number of input tokens sent to AI model
        completion_tokens: Number of output tokens generated by AI model
        total_tokens: Total tokens (prompt + completion)
    """
    prompt_tokens: int = Field(default=0, ge=0, description="Input tokens")
    completion_tokens: int = Field(default=0, ge=0, description="Output tokens")
    total_tokens: int = Field(default=0, ge=0, description="Total tokens")

    model_config = ConfigDict(json_schema_extra={
        "example": {
            "prompt_tokens": 5000,
            "completion_tokens": 2000,
            "total_tokens": 7000
        }
    })


class ProgressUpdate(BaseModel):
    """
    Real-time progress update for conversion job.

    Designed for efficient polling: lightweight payload with only essential progress data.

    Attributes:
        job_id: Job identifier (UUID)
        status: Current job status (QUEUED, ANALYZING, PROCESSING, COMPLETED, FAILED)
        progress_percentage: Conversion progress (0-100)
        current_stage: Current pipeline stage identifier
        stage_description: User-friendly stage description
        elements_detected: Live count of detected elements
        estimated_time_remaining: Seconds remaining (optional, calculated from average)
        estimated_cost: Estimated AI cost in USD (e.g., 0.15)
        quality_confidence: Quality confidence score (0-100, available after analysis)
        timestamp: Timestamp of this progress update
    """
    job_id: str = Field(description="Job UUID")
    status: str = Field(description="Job status: QUEUED, ANALYZING, PROCESSING, COMPLETED, FAILED")
    progress_percentage: int = Field(ge=0, le=100, description="Conversion progress (0-100)")
    current_stage: str = Field(
        description="Current pipeline stage: upload, layout_analysis, structure, epub_generation, quality_scoring"
    )
    stage_description: str = Field(description="User-friendly stage description")
    elements_detected: ElementsDetected = Field(default_factory=ElementsDetected)
    estimated_time_remaining: Optional[int] = Field(
        default=None,
        description="Estimated seconds remaining (optional)"
    )
    estimated_cost: Optional[float] = Field(
        default=None,
        description="Estimated AI cost in USD (e.g., 0.15)"
    )
    quality_confidence: Optional[int] = Field(
        default=None,
        ge=0,
        le=100,
        description="Quality confidence score (0-100)"
    )
    timestamp: datetime = Field(default_factory=datetime.utcnow)

    @field_validator('progress_percentage')
    @classmethod
    def validate_progress(cls, v: int) -> int:
        """Validate progress percentage is between 0 and 100."""
        if not 0 <= v <= 100:
            raise ValueError("Progress percentage must be between 0 and 100")
        return v

    @field_validator('status')
    @classmethod
    def validate_status(cls, v: str) -> str:
        """Validate status is one of the allowed values."""
        allowed_statuses = {
            "UPLOADED", "QUEUED", "ANALYZING", "EXTRACTING",
            "STRUCTURING", "GENERATING", "PROCESSING",
            "COMPLETED", "FAILED", "CANCELLED"
        }
        if v not in allowed_statuses:
            raise ValueError(f"Status must be one of: {', '.join(sorted(allowed_statuses))}")
        return v

    model_config = ConfigDict(json_schema_extra={
        "example": {
            "job_id": "123e4567-e89b-12d3-a456-426614174000",
            "status": "PROCESSING",
            "progress_percentage": 50,
            "current_stage": "layout_analysis",
            "stage_description": "Detecting tables and images...",
            "elements_detected": {
                "tables": 12,
                "images": 8,
                "equations": 5,
                "chapters": 0
            },
            "estimated_time_remaining": 45,
            "estimated_cost": 0.12,
            "quality_confidence": 94,
            "timestamp": "2025-12-14T10:30:00Z"
        }
    })
